SRCS += $(shell find $(SRCDIR)/kernel 	 -name '*.cpp') 	
SRCS += $(shell find $(SRCDIR)/lib 	 -name '*.cpp') 	
SRCS += $(shell find $(SRCDIR)/cpp 	 -name '*.cpp') 	
SRCS += $(shell find $(SRCDIR)/multiboot -name '*.cpp') 	
SRCS += $(shell find $(SRCDIR)/hal/x86 	 -name '*.cpp')

SRCS += $(shell find $(SRCDIR)/kernel 	 -name '*.c') 	
SRCS += $(shell find $(SRCDIR)/lib 	 -name '*.c') 	
SRCS += $(shell find $(SRCDIR)/cpp 	 -name '*.c') 	
SRCS += $(shell find $(SRCDIR)/multiboot -name '*.c') 	
SRCS += $(shell find $(SRCDIR)/hal/x86 	 -name '*.c') 

SRCS += $(shell find $(SRCDIR)/kernel 	 -name '*.S') 	
SRCS += $(shell find $(SRCDIR)/lib 	 -name '*.S') 	
SRCS += $(shell find $(SRCDIR)/cpp 	 -name '*.S') 	
SRCS += $(shell find $(SRCDIR)/multiboot -name '*.S') 	
SRCS += $(shell find $(SRCDIR)/hal/x86 	 -name '*.S') 	

OBJS = $(addsuffix .o,$(basename $(SRCS)))

LINK = -T $(BASEDIR)/config/arch_x86/quartus-x86.ld

INCL = -I $(SRCDIR)/lib/libc/include -I $(SRCDIR)/lib/libc++/include -I $(SRCDIR)/lib/tools/include -I $(SRCDIR)/config

PREPROC	= -D ARCH_X86 -D ARCH_USE_MULTIBOOT -D OUTPUT_SCREEN
