BASEDIR  = .
SRCDIR	 = $(BASEDIR)/src
BUILDDIR = $(BASEDIR)/bin

SRCS := $(shell find -name '*.cpp') \
	$(shell find -name '*.c')   \
	$(shell find -name '*.S')

OBJS = $(addsuffix .o,$(basename $(SRCS)))

INCLUDE = -I $(SRCDIR)/lib/libc/include -I $(SRCDIR)/lib/libc++/include -I $(SRCDIR)/definitions
