SRCS += $(shell find $(SRCDIR)/kernel 	 -name '*.cpp') 	
SRCS += $(shell find $(SRCDIR)/lib 	 -name '*.cpp') 	
SRCS += $(shell find $(SRCDIR)/cpp 	 -name '*.cpp') 	

SRCS += $(shell find $(SRCDIR)/hal/rpi 	 -name '*.cpp')

SRCS += $(shell find $(SRCDIR)/kernel 	 -name '*.c') 	
SRCS += $(shell find $(SRCDIR)/lib 	 -name '*.c') 	
SRCS += $(shell find $(SRCDIR)/cpp 	 -name '*.c') 	

SRCS += $(shell find $(SRCDIR)/hal/rpi	 -name '*.c') 

SRCS += $(shell find $(SRCDIR)/kernel 	 -name '*.S') 	
SRCS += $(shell find $(SRCDIR)/lib 	 -name '*.S') 	
SRCS += $(shell find $(SRCDIR)/cpp 	 -name '*.S') 	

SRCS += $(shell find $(SRCDIR)/hal/rpi 	 -name '*.S') 	

OBJS = $(addsuffix .o,$(basename $(SRCS)))

LINK = -T $(BASEDIR)/config/arch_rpi/quartus-rpi.ld

INCL = -I $(SRCDIR)/lib/libc/include -I $(SRCDIR)/lib/libc++/include -I $(SRCDIR)/config

PREPROC	= -D ARCH_RPI -D OUTPUT_SERIAL
